function N = two_link_gravity_matrix(g,l1,l2,m1,m2,th1,th2)
%TWO_LINK_GRAVITY_MATRIX
%    N = TWO_LINK_GRAVITY_MATRIX(G,L1,L2,M1,M2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    10-Mar-2018 00:14:34

t2 = sin(th1);
t3 = cos(th1);
t4 = sin(th2);
t5 = cos(th2);
t6 = l1+l2;
t7 = l2.*(1.0./2.0);
t8 = l1+t7;
t9 = t3.*t4;
t10 = t2.*t5;
t11 = t9+t10;
t12 = t3.*t4.*t6;
N = [g.*m2.*(t12+l1.*t2-t8.*t11+t2.*t6.*(t5-1.0))+g.*l1.*m1.*t2.*(1.0./2.0);g.*m2.*(t12-t8.*t11+t2.*t5.*t6)];
